name: oc-backend-data
namespace: ffisa-dev

image:
  repository: fabricioph2/oc-backend-data
  tag: 6

replicas: 1

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  enabled: true
  port: 80
  targetPort: 3005

route:
  enabled: false

hpa:
  enabled: false

statefulset:
  enabled: false

env:
  - name: MONGO_URI
    value: "mongodb://oc-database:27017/comments_db"
  - name: PORT
    value: "3005"

networkPolicies:
  enabled: true
